// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/margin-auth/AuthScreen.tsx": () => import("../components/mockups/margin-auth/AuthScreen.tsx"),
  "./components/mockups/margin-auth/DarkEditorial.tsx": () => import("../components/mockups/margin-auth/DarkEditorial.tsx"),
  "./components/mockups/margin-auth/TerracottaWarm.tsx": () => import("../components/mockups/margin-auth/TerracottaWarm.tsx")
};
